config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {registrations: 'registrations', sessions: 'sessions', confirmations: 'confirmations'}, path: '', :skip => [:confirmations, :passwords]

  devise_scope :user do
    get '/new_confirmation' => 'confirmations#new', :as => :new_user_confirmation
    post '/confirmation' => 'confirmations#create', :as => :user_confirmation
    get '/confirmation' => 'confirmations#show', :as => :show_user_confirmation

    get '/new_password' => 'devise/passwords#new', :as => :new_user_password
    post '/password' => 'devise/passwords#create', :as => :user_password
    get '/password' => 'devise/passwords#edit', :as => :edit_user_password
    put '/password' => 'devise/passwords#update', :as => :update_user_password
  end

  controller :application do
    get '404' => :error_404
    get '422' => :error_422
    get '500' => :error_500
  end

  controller :browse do
    get '/programmers' => :programmers, as: 'show_programmers'
    get '/employers' => :employers, as: 'show_employers'

    get '/programmer_search' => :programmer_search, as: 'search_programmers'
    get '/employer_search' => :employer_search, as: 'search_employers'
    get '/job_search' => :job_search, as: 'search_jobs'
  end

  controller :contact do
    get '/user/:username/c' => :contact_page, as: 'show_user_contact_page'
    post '/contact' => :send_contact_request, as: 'send_contact_request'
  end

  controller :jobs do
    post '/job/create' => :create, as: 'create_job'
    delete '/job/destroy' => :destroy, as: 'destroy_job'
    get '/job/:id' => :show, as: 'show_job'
    get '/job/:id/edit' => :edit, as: 'edit_job'
    patch '/job/:id/update' => :update, as: 'update_job'
  end

  controller :user_info do
    get '/user/:username' => :show, as: 'show_user'
  end

  controller :watchings do
    post '/watching/create' => :create, as: 'create_watching'
    delete '/watching/destroy' => :destroy, as: 'destroy_watching'
  end

  controller :works do
    post '/work/create' => :create, as: 'create_work'
    delete '/work/:id/destroy' => :destroy, as: 'destroy_work'
    get '/work/:id/edit' => :edit, as: 'edit_work'
    patch '/work/:id/update' => :update, as: 'update_work'
  end

  root 'browse#jobs'

end

app/controllers/user_info_controller.rb
class UserInfoController < ApplicationController

  def index
    if user_signed_in?
      @jobs = current_user.watching_jobs.order(:created_at).paginate(page: params[:page])
      @possible_jobs = Job.all.order(created_at: :desc).take(5)

      if current_user.is_employer
        @job = Job.new
      else
        @work = Work.new
      end
    end
  end

  def show
    @user = User.where('LOWER(username) = ?', params[:username].downcase).first

    if !@user
      redirect_to root_path
    else
      if @user.is_employer
        @jobs = @user.jobs.order(created_at: :desc)
        @job = Job.new
      else
        @works = @user.works.order(:title)
        @work = Work.new
      end
    end
  end

end

app/helpers/user_info_helper.rb
module UserInfoHelper
end

app/views/user_info/index.html.haml
- if !user_signed_in?
  .col-md-12
    .jumbotron.text-center
      %h1= t('join_us')
      %br
      %p
        The Awesome Inc Jobs Board is a place to find out about tech job openings in Lexington, Louisville, Cincinnati/NKY, and throughout Kentucky. Employers can use this site to add and manage job listings, and and people seeking jobs can post info like experience and GitHub/LinkedIn profiles. Feel free to email
        %a{href:'mailto:jobs.awesomeinc.org'} jobs@awesomeinc.org
        for any assistance.
      %br
      = link_to "<span class='glyphicon glyphicon-user'></span> #{t('sign_in')}".html_safe, new_user_session_path ,class: 'btn btn-primary btn-lg'
      %br
      %br
      = link_to "<span class='glyphicon glyphicon-plus'></span> #{t('sign_up')}".html_safe, new_user_registration_path, class: 'btn btn-lg btn-success'
- else
  .col-md-4
    .content.text-center
      %h2= t('welcome')
      %h3
        = image_tag current_user.avatar_url(:smaller), class: 'img-circle smaller'
        = link_to t('your_profile'), show_user_path(username: current_user.username)
      %button{class: 'btn btn-success navbar-btn btn-lg', 'data-toggle' => "modal", 'data-target' => "#myModal"}
        = current_user.is_employer ? t('new_job') : t('new_work')
        %span.glyphicon.glyphicon-plus

  .col-md-8
    - if @jobs.count > 0 or @possible_jobs.count == 0
      .content
        %h1.text-center= t('watching_jobs')
        %br
        .text-center
          = will_paginate @jobs, param_name: :page
          - @jobs.each do |j|
            %h2
              = link_to j.title, show_job_path(id: j.id)
            %p= truncate(j.description, length: 50)
            = image_tag j.user.avatar_url(:thumb), class: 'img-circle thumb'
            - if j.user.company and !j.user.company.blank?
              = link_to "#{t('by')} #{j.user.name} #{t('at')} #{j.user.company}", show_user_path(username: j.user.username)
            - else
              = link_to j.user.name, show_user_path(username: j.user.username)
          %br
          = will_paginate @jobs, param_name: :page
    - if @possible_jobs.count > 0
      .content
        %h1.text-center= t('new_jobs')
        %br
        .text-center
          = link_to t('see_all_jobs'), show_jobs_path
        .text-center
          - @possible_jobs.each do |j|
            %h2
              = link_to j.title, show_job_path(id: j.id)
            %p= truncate(j.description, length: 50)
            = image_tag j.user.avatar_url(:thumb), class: 'img-circle thumb'
            - if j.user.company and !j.user.company.blank?
              = link_to "#{t('by')} #{j.user.name} #{t('at')} #{j.user.company}", show_user_path(username: j.user.username)
            - else
              = link_to j.user.name, show_user_path(username: j.user.username)
          - if @possible_jobs.count == 0
            %i= t('nothing_here')
        %br
        .text-center
          = link_to t('see_all_jobs'), show_jobs_path

  #myModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
    .modal-dialog
      .modal-content
        .modal-header
          %button.close{"data-dismiss" => "modal", type: "button"}
            %span{"aria-hidden" => "true"} ×
            %span.sr-only= t('close')
          %h4#myModalLabel.modal-title.text-center= current_user.is_employer ? t('new_job') : t('new_work')
        .modal-body
          - if current_user.is_employer
            = form_for @job, url: create_job_path, remote: true do |f|
              #job-title-group.form-group
                = f.label :title, class: 'control-label'
                = f.text_field :title, class: 'form-control input-lg', autocomplete: 'off', placeholder: t('job_title_placeholder'), maxlength: 50
              %br
              .form-group
                = f.label :url, class: 'control-label'
                = f.text_field :url, class: 'form-control input-lg', autocomplete: 'off', placeholder: t('website_placeholder'), maxlength: 100
              %br
              #job-description-group.form-group
                = f.label :description, class: 'control-label'
                = f.text_area :description, class: 'form-control input-lg', autocomplete: 'off', rows: 7, placeholder: t('job_description_placeholder'), maxlength: 1000
              %br
              %div.text-center
                %button{type: 'submit', class: 'btn btn-success btn-lg'}= "<span class='glyphicon glyphicon-plus'></span> #{t('add')}".html_safe
          - else
            = form_for @work, url: create_work_path, remote: true do |f|
              #work-title-group.form-group
                = f.label :title, class: 'control-label'
                = f.text_field :title, class: 'form-control input-lg', autocomplete: 'off', placeholder: t('work_title_placeholder'), maxlength: 50
              %br
              #work-url-group.form-group
                = f.label :url, class: 'control-label'
                = f.text_field :url, class: 'form-control input-lg', autocomplete: 'off', placeholder: t('work_url_placeholder'), maxlength: 100
              %br
              #work-description-group.form-group
                = f.label :description, class: 'control-label'
                = f.text_area :description, class: 'form-control input-lg', autocomplete: 'off', rows: 7, placeholder: t('work_description_placeholder'), maxlength: 1000
              %br
              %div.text-center
                %button{type: 'submit', class: 'btn btn-success btn-lg'}= "<span class='glyphicon glyphicon-plus'></span> #{t('add')}".html_safe

app/views/user_info/show.html.haml
.col-md-3
.col-md-6
  .content
    .text-center
      = image_tag @user.avatar_url(:smaller), class: 'img-circle smaller'
      %h1= @user.name
      - if @user.company and !@user.company.blank?
        %h4
          %i= @user.company
      - if @user.description and !@user.description.blank?
        %br
        %h3= simple_format @user.description
        %br
      - if @user.website and !@user.website.blank?
        %h4
          = t('website') + ': '
          = auto_link @user.website
      - if @user.phone and !@user.phone.blank?
        %h4= "#{t('phone_number')}: #{@user.phone}"
      - if @user.address and !@user.address.blank?
        %h4= "#{t('address')}: #{@user.address}"
      - if !@user.is_employer and @user.resume and !@user.resume.blank?
        %h3.text-center= link_to t('resume'), @user.resume_url
      - if @user != current_user
        %br
        %br
        = link_to t('contact'), show_user_contact_page_path(username: @user.username), class: 'btn btn-lg btn-primary'
        %br
      %br
    - if @user == current_user
      .text-center
        %button{class: 'btn btn-success navbar-btn btn-lg', 'data-toggle' => "modal", 'data-target' => "#myModal"}
          = current_user.is_employer ? t('new_job') : t('new_work')
          %span.glyphicon.glyphicon-plus
    - if @user.is_employer
      .text-center
        %h2= t('jobs')
        - @jobs.each do |j|
          %h2
            = link_to j.title, show_job_path(id: j.id)
          - if j.url
            = auto_link j.url
          %p= truncate(j.description, length: 50)
          - if @user == current_user
            = link_to t('edit'), edit_job_path(id: j.id)
            %br
            = link_to t('delete'), destroy_job_path(id: j.id), method: :delete
        - if @jobs.count == 0
          %i= t('nothing_here')
    - else
      .text-center
        %h2= t('works')
        - @works.each do |w|
          %h2
            %a{href: w.url}= w.title
          %p= simple_format w.description
          - if current_user == w.user
            = link_to t('edit'), edit_work_path(id: w.id)
            %br
            = link_to t('delete'), destroy_work_path(id: w.id), method: :delete
        - if @works.count == 0
          %i= t('nothing_here')
      %br

    - if @user == current_user
      #myModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
        .modal-dialog
          .modal-content
            .modal-header
              %button.close{"data-dismiss" => "modal", type: "button"}
                %span{"aria-hidden" => "true"} ×
                %span.sr-only= t('close')
              %h4#myModalLabel.modal-title.text-center= current_user.is_employer ? t('new_job') : t('new_work')
            .modal-body
              - if current_user.is_employer
                = form_for @job, url: create_job_path, remote: true do |f|
                  #job-title-group.form-group
                    = f.label :title, class: 'control-label'
                    = f.text_field :title, class: 'form-control input-lg', autocomplete: 'off', placeholder: t('job_title_placeholder'), maxlength: 50
                  %br
                  .form-group
                    = f.label :url, class: 'control-label'
                    = f.text_field :url, class: 'form-control input-lg', autocomplete: 'off', placeholder: t('website_placeholder'), maxlength: 100
                  %br
                  #job-description-group.form-group
                    = f.label :description, class: 'control-label'
                    = f.text_area :description, class: 'form-control input-lg', autocomplete: 'off', rows: 7, placeholder: t('job_description_placeholder'), maxlength: 1000
                  %br
                  %div.text-center
                    %button{type: 'submit', class: 'btn btn-success btn-lg'}= "<span class='glyphicon glyphicon-plus'></span> #{t('add')}".html_safe
              - else
                = form_for @work, url: create_work_path, remote: true do |f|
                  #work-title-group.form-group
                    = f.label :title, class: 'control-label'
                    = f.text_field :title, class: 'form-control input-lg', autocomplete: 'off', placeholder: t('work_title_placeholder'), maxlength: 50
                  %br
                  #work-url-group.form-group
                    = f.label :url, class: 'control-label'
                    = f.text_field :url, class: 'form-control input-lg', autocomplete: 'off', placeholder: t('work_url_placeholder'), maxlength: 100
                  %br
                  #work-description-group.form-group
                    = f.label :description, class: 'control-label'
                    = f.text_area :description, class: 'form-control input-lg', autocomplete: 'off', rows: 7, placeholder: t('work_description_placeholder'), maxlength: 1000
                  %br
                  %div.text-center
                    %button{type: 'submit', class: 'btn btn-success btn-lg'}= "<span class='glyphicon glyphicon-plus'></span> #{t('add')}".html_safe
        
.col-md-3