config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {registrations: 'registrations', sessions: 'sessions', confirmations: 'confirmations'}, path: '', :skip => [:confirmations, :passwords]

  devise_scope :user do
    get '/new_confirmation' => 'confirmations#new', :as => :new_user_confirmation
    post '/confirmation' => 'confirmations#create', :as => :user_confirmation
    get '/confirmation' => 'confirmations#show', :as => :show_user_confirmation

    get '/new_password' => 'devise/passwords#new', :as => :new_user_password
    post '/password' => 'devise/passwords#create', :as => :user_password
    get '/password' => 'devise/passwords#edit', :as => :edit_user_password
    put '/password' => 'devise/passwords#update', :as => :update_user_password
  end

  controller :application do
    get '404' => :error_404
    get '422' => :error_422
    get '500' => :error_500
  end

  controller :browse do
    get '/programmers' => :programmers, as: 'show_programmers'
    get '/employers' => :employers, as: 'show_employers'

    get '/programmer_search' => :programmer_search, as: 'search_programmers'
    get '/employer_search' => :employer_search, as: 'search_employers'
    get '/job_search' => :job_search, as: 'search_jobs'
  end

  controller :contact do
    get '/user/:username/c' => :contact_page, as: 'show_user_contact_page'
    post '/contact' => :send_contact_request, as: 'send_contact_request'
  end

  controller :jobs do
    post '/job/create' => :create, as: 'create_job'
    delete '/job/destroy' => :destroy, as: 'destroy_job'
    get '/job/:id' => :show, as: 'show_job'
    get '/job/:id/edit' => :edit, as: 'edit_job'
    patch '/job/:id/update' => :update, as: 'update_job'
  end

  controller :user_info do
    get '/user/:username' => :show, as: 'show_user'
  end

  controller :watchings do
    post '/watching/create' => :create, as: 'create_watching'
    delete '/watching/destroy' => :destroy, as: 'destroy_watching'
  end

  controller :works do
    post '/work/create' => :create, as: 'create_work'
    delete '/work/:id/destroy' => :destroy, as: 'destroy_work'
    get '/work/:id/edit' => :edit, as: 'edit_work'
    patch '/work/:id/update' => :update, as: 'update_work'
  end

  root 'browse#jobs'

end

app/models/work.rb
class Work < ActiveRecord::Base

  before_validation :preval

  belongs_to :user

  validates :title, presence: :true, length: { maximum: 50 }
  validates :description, presence: :true, length: { maximum: 400 }
  validates :url, presence: :true, length: { maximum: 100 }

  private
    def preval
      if self.title
        self.title = self.title.strip
      end

      if self.description
        self.description = self.description.strip
      end

      if self.url
        self.url = self.url.strip.delete(' ')
        if !self.url.blank?
          if !self.url.start_with?('http://') and !self.url.start_with?('https://') and !self.url.start_with?('www.')
            self.url = 'http://' + self.url
          end
        end
      end
    end


end

app/controllers/works_controller.rb
class WorksController < ApplicationController

  before_filter :authenticate_user!

  def edit
    @work = Work.where(user: current_user, id: params[:id]).first

    if !@work
      redirect_to show_user_path(username: current_user.username)
    end
  end

  def create
    if params[:work]
      w = Work.new(user: current_user, title: params[:work][:title], description: params[:work][:description], url: params[:work][:url])

      respond_to do |format|
        if !current_user.is_employer and w.save
          format.html { redirect_to show_user_path(id: current_user.id) }
          format.js { @vals = { success: true, url: show_user_path(username: current_user.username) } }
        else
          format.html { redirect_to show_user_path(username: current_user.username) }
          format.js { @vals = { success: false, work: w } }
        end
      end
    else
      redirect_to root_path
    end
  end

  def update
    w = Work.where(user: current_user, id: params[:id]).first

    respond_to do |format|
      if params[:work] and w and w.update(title: params[:work][:title], description: params[:work][:description], url: params[:work][:url])
        format.html { redirect_to show_user_path(id: current_user.id) }
        format.js { @vals = { success: true, url: show_user_path(username: current_user.username) } }
      else
        format.html { redirect_to show_user_path(username: current_user.username) }
        format.js { @vals = { success: false, work: w } }
      end
    end
  end

  def destroy

    w = Work.where(user: current_user, id: params[:id]).first

    respond_to do |format|
      if w and w.destroy
        format.html { redirect_to show_user_path(username: current_user.username) }
      else
        format.html { redirect_to show_user_path(username: current_user.username) }
      end
    end


  end
  
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/works/create.js.erb
// AJAX for when someone tries to create a new work.

<% if @vals[:success] %>
  window.location.replace("<%= escape_javascript(@vals[:url].to_s) %>");
<% else %>
  <% if @vals[:work].errors[:title].count > 0 %>
    // make sure it wasn't already done
    if (!($('#work-title-group > span.glyphicon.glyphicon-remove.form-control-feedback').length)) {
      $('#work-title-group').append("<span class='glyphicon glyphicon-remove form-control-feedback'></span>");
      $('#work-title-group').addClass('has-error');
      $('#work-title-group').addClass('has-feedback');
    }
  <% else %>
    // remove it if we don't need it
    $('#work-title-group > span.glyphicon.glyphicon-remove.form-control-feedback').remove();
    $('#work-title-group').attr('class', 'form-group');
  <% end %>

  <% if @vals[:work].errors[:url].count > 0 %>
    // make sure it wasn't already done
    if (!($('#work-url-group > span.glyphicon.glyphicon-remove.form-control-feedback').length)) {
      $('#work-url-group').append("<span class='glyphicon glyphicon-remove form-control-feedback'></span>");
      $('#work-url-group').addClass('has-error');
      $('#work-url-group').addClass('has-feedback');
    }
  <% else %>
    // remove it if we don't need it
    $('#work-url-group > span.glyphicon.glyphicon-remove.form-control-feedback').remove();
    $('#work-url-group').attr('class', 'form-group');
  <% end %>

  <% if @vals[:work].errors[:description].count > 0 %>
    // make sure it wasn't already done
    if (!($('#work-description-group > span.glyphicon.glyphicon-remove.form-control-feedback').length)) {
      $('#work-description-group').append("<span class='glyphicon glyphicon-remove form-control-feedback'></span>");
      $('#work-description-group').addClass('has-error');
      $('#work-description-group').addClass('has-feedback');
    }
  <% else %>
    // remove it if we don't need it
    $('#work-description-group > span.glyphicon.glyphicon-remove.form-control-feedback').remove();
    $('#work-description-group').attr('class', 'form-group');
  <% end %>
<% end %>

app/views/works/edit.html.haml
.col-md-3
.col-md-6
  .content
    %h2.text-center= t('update_work')
    %br
    = form_for @work, url: update_work_path, method: :patch, remote: true do |f|
      #work-title-group.form-group
        = f.label :title, class: 'control-label'
        = f.text_field :title, class: 'form-control input-lg', autocomplete: 'off', placeholder: t('work_title_placeholder')
      %br
      #work-url-group.form-group
        = f.label :url, class: 'control-label'
        = f.text_field :url, class: 'form-control input-lg', autocomplete: 'off', placeholder: t('work_url_placeholder')
      %br
      #work-description-group.form-group
        = f.label :description, class: 'control-label'
        = f.text_area :description, class: 'form-control input-lg', autocomplete: 'off', rows: 7, placeholder: t('work_description_placeholder')
      %br
      %div.text-center
        %button{type: 'submit', class: 'btn btn-success btn-lg'}= "<span class='glyphicon glyphicon-plus'></span> #{t('save')}".html_safe
.col-md-3

app/views/works/update.js.erb
// AJAX for when someone tries to create a new work.

<% if @vals[:success] %>
  window.location.replace("<%= escape_javascript(@vals[:url].to_s) %>");
<% else %>
  <% if @vals[:work].errors[:title].count > 0 %>
    // make sure it wasn't already done
    if (!($('#work-title-group > span.glyphicon.glyphicon-remove.form-control-feedback').length)) {
      $('#work-title-group').append("<span class='glyphicon glyphicon-remove form-control-feedback'></span>");
      $('#work-title-group').addClass('has-error');
      $('#work-title-group').addClass('has-feedback');
    }
  <% else %>
    // remove it if we don't need it
    $('#work-title-group > span.glyphicon.glyphicon-remove.form-control-feedback').remove();
    $('#work-title-group').attr('class', 'form-group');
  <% end %>

  <% if @vals[:work].errors[:url].count > 0 %>
    // make sure it wasn't already done
    if (!($('#work-url-group > span.glyphicon.glyphicon-remove.form-control-feedback').length)) {
      $('#work-url-group').append("<span class='glyphicon glyphicon-remove form-control-feedback'></span>");
      $('#work-url-group').addClass('has-error');
      $('#work-url-group').addClass('has-feedback');
    }
  <% else %>
    // remove it if we don't need it
    $('#work-url-group > span.glyphicon.glyphicon-remove.form-control-feedback').remove();
    $('#work-url-group').attr('class', 'form-group');
  <% end %>

  <% if @vals[:work].errors[:description].count > 0 %>
    // make sure it wasn't already done
    if (!($('#work-description-group > span.glyphicon.glyphicon-remove.form-control-feedback').length)) {
      $('#work-description-group').append("<span class='glyphicon glyphicon-remove form-control-feedback'></span>");
      $('#work-description-group').addClass('has-error');
      $('#work-description-group').addClass('has-feedback');
    }
  <% else %>
    // remove it if we don't need it
    $('#work-description-group > span.glyphicon.glyphicon-remove.form-control-feedback').remove();
    $('#work-description-group').attr('class', 'form-group');
  <% end %>
<% end %>