config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {registrations: 'registrations', sessions: 'sessions', confirmations: 'confirmations'}, path: '', :skip => [:confirmations, :passwords]

  devise_scope :user do
    get '/new_confirmation' => 'confirmations#new', :as => :new_user_confirmation
    post '/confirmation' => 'confirmations#create', :as => :user_confirmation
    get '/confirmation' => 'confirmations#show', :as => :show_user_confirmation

    get '/new_password' => 'devise/passwords#new', :as => :new_user_password
    post '/password' => 'devise/passwords#create', :as => :user_password
    get '/password' => 'devise/passwords#edit', :as => :edit_user_password
    put '/password' => 'devise/passwords#update', :as => :update_user_password
  end

  controller :application do
    get '404' => :error_404
    get '422' => :error_422
    get '500' => :error_500
  end

  controller :browse do
    get '/programmers' => :programmers, as: 'show_programmers'
    get '/employers' => :employers, as: 'show_employers'

    get '/programmer_search' => :programmer_search, as: 'search_programmers'
    get '/employer_search' => :employer_search, as: 'search_employers'
    get '/job_search' => :job_search, as: 'search_jobs'
  end

  controller :contact do
    get '/user/:username/c' => :contact_page, as: 'show_user_contact_page'
    post '/contact' => :send_contact_request, as: 'send_contact_request'
  end

  controller :jobs do
    post '/job/create' => :create, as: 'create_job'
    delete '/job/destroy' => :destroy, as: 'destroy_job'
    get '/job/:id' => :show, as: 'show_job'
    get '/job/:id/edit' => :edit, as: 'edit_job'
    patch '/job/:id/update' => :update, as: 'update_job'
  end

  controller :user_info do
    get '/user/:username' => :show, as: 'show_user'
  end

  controller :watchings do
    post '/watching/create' => :create, as: 'create_watching'
    delete '/watching/destroy' => :destroy, as: 'destroy_watching'
  end

  controller :works do
    post '/work/create' => :create, as: 'create_work'
    delete '/work/:id/destroy' => :destroy, as: 'destroy_work'
    get '/work/:id/edit' => :edit, as: 'edit_work'
    patch '/work/:id/update' => :update, as: 'update_work'
  end

  root 'browse#jobs'

end

app/models/job.rb
class Job < ActiveRecord::Base

  before_validation :preval
  before_create :not_too_many

  belongs_to :user

  validates :title, presence: :true, length: { maximum: 50 }
  validates :description, presence: :true, length: { maximum: 1000 }
  validates :url, length: { maximum: 100 }

  private
    def preval
      if self.title
        self.title = self.title.strip
      end

      if self.description
        self.description = self.description.strip
      end

      if self.url
        self.url = self.url.strip.delete(' ')
        if !self.url.blank?
          if !self.url.start_with?('http://') and !self.url.start_with?('https://') and !self.url.start_with?('www.')
            self.url = 'http://' + self.url
          end
        end
      end
    end

    def not_too_many
      count = Job.where(user_id: self.user_id, created_at: 1.hour.ago..DateTime.now).count
      count <= 10
    end


end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  before_filter :authenticate_user!, except: [:index, :show]

  def show
    @job = Job.where(id: params[:id]).first

    if !@job
      redirect_to root_path
    elsif user_signed_in?
      @watching = Watching.where(user: current_user, job: @job).first
    end
  end

  def edit
    @job = Job.where(user: current_user, id: params[:id]).first

    if !@job
      redirect_to show_user_path(username: current_user.username)
    end
  end

  def create
    if params[:job]
      j = Job.new(title: params[:job][:title], description: params[:job][:description], url: params[:job][:url], user: current_user)

      respond_to do |format|
        if current_user.is_employer and j.save
          format.html { redirect_to show_job_path(id: j.id) }
          format.js { @vals = {success: true, url: show_user_path(username: current_user.username) } }
        else
          format.html { redirect_to show_user_path(username: current_user.username) }
          format.js { @vals = {success: false, job: j} }

        end
      end
    else
      redirect_to root_path
    end
  end

  def destroy
    j = Job.where(user: current_user, id: params[:id]).first

    respond_to do |format|
      if j and j.destroy
        format.html { redirect_to show_user_path(username: current_user.username) }
      else
        format.html { redirect_to show_user_path(username: current_user.username) }
      end
    end
  end

  def update
    j = Job.where(user: current_user, id: params[:id]).first

    respond_to do |format|
      if params[:job] and j and j.update(title: params[:job][:title], description: params[:job][:description], url: params[:job][:url])
        format.html { redirect_to show_user_path(username: current_user.username) }
        format.js { @vals = { success: true, url: show_user_path(username: current_user.username) } }
      else
        format.html { redirect_to show_user_path(username: current_user.username) }
        format.js { @vals = { success: false, job: j } }
      end
    end
  end

end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/create.js.erb
// AJAX for when someone tries to create a new job.

<% if @vals[:success] %>
  window.location.replace("<%= escape_javascript(@vals[:url].to_s) %>");
<% else %>
  <% if @vals[:job].errors[:title].count > 0 %>
    // make sure it wasn't already done
    if (!($('#job-title-group > span.glyphicon.glyphicon-remove.form-control-feedback').length)) {
      $('#job-title-group').append("<span class='glyphicon glyphicon-remove form-control-feedback'></span>");
      $('#job-title-group').addClass('has-error');
      $('#job-title-group').addClass('has-feedback');
    }
  <% else %>
    // remove it if we don't need it
    $('#job-title-group > span.glyphicon.glyphicon-remove.form-control-feedback').remove();
    $('#job-title-group').attr('class', 'form-group');
  <% end %>

  <% if @vals[:job].errors[:description].count > 0 %>
    // make sure it wasn't already done
    if (!($('#job-description-group > span.glyphicon.glyphicon-remove.form-control-feedback').length)) {
      $('#job-description-group').append("<span class='glyphicon glyphicon-remove form-control-feedback'></span>");
      $('#job-description-group').addClass('has-error');
      $('#job-description-group').addClass('has-feedback');
    }
  <% else %>
    // remove it if we don't need it
    $('#job-description-group > span.glyphicon.glyphicon-remove.form-control-feedback').remove();
    $('#job-description-group').attr('class', 'form-group');
  <% end %>
<% end %>

app/views/jobs/edit.html.haml
.col-md-3
.col-md-6
  .content
    %h2.text-center= t('update_job')
    %br
    = form_for @job, url: update_job_path, method: :patch, remote: true do |f|
      #job-title-group.form-group
        = f.label :title, class: 'control-label'
        = f.text_field :title, class: 'form-control input-lg', autocomplete: 'off', placeholder: t('job_title_placeholder')
      %br
      .form-group
        = f.label :url, class: 'control-label'
        = f.text_field :url, class: 'form-control input-lg', autocomplete: 'off', placeholder: t('website_placeholder'), maxlength: 100
      %br
      #job-description-group.form-group
        = f.label :description, class: 'control-label'
        = f.text_area :description, class: 'form-control input-lg', autocomplete: 'off', rows: 7, placeholder: t('job_description_placeholder')
      %br
      %div.text-center
        %button{type: 'submit', class: 'btn btn-success btn-lg'}= "<span class='glyphicon glyphicon-plus'></span> #{t('save')}".html_safe
.col-md-3

app/views/jobs/show.html.haml
.col-md-2
.col-md-8
  .content
    %h1.text-center= @job.title
    .text-center
      = image_tag @job.user.avatar_url(:thumb), class: 'img-circle thumb'
      - if @job.user.company and !@job.user.company.blank?
        = link_to "#{t('by')} #{@job.user.name} #{t('at')} #{@job.user.company}", show_user_path(username: @job.user.username)
      - else
        = link_to @job.user.name, show_user_path(username: @job.user.username)
    - if @job.url and !@job.url.blank?
      .text-center
        = auto_link @job.url
    %br
    - if user_signed_in?
      #watching_button.text-center
        - if @watching
          = link_to('<span class="glyphicon glyphicon-eye-close"></span>'.html_safe, destroy_watching_path(id: @watching.id), class: 'btn btn-lg btn-danger', method: :delete, remote: true)
        - else
          = link_to('<span class="glyphicon glyphicon-eye-open"></span>'.html_safe, create_watching_path(id: @job.id), class: 'btn btn-lg btn-primary', method: :post, remote: true)
    .text-center
      %p= simple_format @job.description
.col-md-2

app/views/jobs/update.js.erb
// AJAX for when someone updates a job.

<% if @vals[:success] %>
  window.location.replace("<%= escape_javascript(@vals[:url].to_s) %>");
<% else %>
  <% if @vals[:job].errors[:title].count > 0 %>
    // make sure it wasn't already done
    if (!($('#job-title-group > span.glyphicon.glyphicon-remove.form-control-feedback').length)) {
      $('#job-title-group').append("<span class='glyphicon glyphicon-remove form-control-feedback'></span>");
      $('#job-title-group').addClass('has-error');
      $('#job-title-group').addClass('has-feedback');
    }
  <% else %>
    // remove it if we don't need it
    $('#job-title-group > span.glyphicon.glyphicon-remove.form-control-feedback').remove();
    $('#job-title-group').attr('class', 'form-group');
  <% end %>

  <% if @vals[:job].errors[:description].count > 0 %>
    // make sure it wasn't already done
    if (!($('#job-description-group > span.glyphicon.glyphicon-remove.form-control-feedback').length)) {
      $('#job-description-group').append("<span class='glyphicon glyphicon-remove form-control-feedback'></span>");
      $('#job-description-group').addClass('has-error');
      $('#job-description-group').addClass('has-feedback');
    }
  <% else %>
    // remove it if we don't need it
    $('#job-description-group > span.glyphicon.glyphicon-remove.form-control-feedback').remove();
    $('#job-description-group').attr('class', 'form-group');
  <% end %>
<% end %>