config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {registrations: 'registrations', sessions: 'sessions', confirmations: 'confirmations'}, path: '', :skip => [:confirmations, :passwords]

  devise_scope :user do
    get '/new_confirmation' => 'confirmations#new', :as => :new_user_confirmation
    post '/confirmation' => 'confirmations#create', :as => :user_confirmation
    get '/confirmation' => 'confirmations#show', :as => :show_user_confirmation

    get '/new_password' => 'devise/passwords#new', :as => :new_user_password
    post '/password' => 'devise/passwords#create', :as => :user_password
    get '/password' => 'devise/passwords#edit', :as => :edit_user_password
    put '/password' => 'devise/passwords#update', :as => :update_user_password
  end

  controller :application do
    get '404' => :error_404
    get '422' => :error_422
    get '500' => :error_500
  end

  controller :browse do
    get '/programmers' => :programmers, as: 'show_programmers'
    get '/employers' => :employers, as: 'show_employers'

    get '/programmer_search' => :programmer_search, as: 'search_programmers'
    get '/employer_search' => :employer_search, as: 'search_employers'
    get '/job_search' => :job_search, as: 'search_jobs'
  end

  controller :contact do
    get '/user/:username/c' => :contact_page, as: 'show_user_contact_page'
    post '/contact' => :send_contact_request, as: 'send_contact_request'
  end

  controller :jobs do
    post '/job/create' => :create, as: 'create_job'
    delete '/job/destroy' => :destroy, as: 'destroy_job'
    get '/job/:id' => :show, as: 'show_job'
    get '/job/:id/edit' => :edit, as: 'edit_job'
    patch '/job/:id/update' => :update, as: 'update_job'
  end

  controller :user_info do
    get '/user/:username' => :show, as: 'show_user'
  end

  controller :watchings do
    post '/watching/create' => :create, as: 'create_watching'
    delete '/watching/destroy' => :destroy, as: 'destroy_watching'
  end

  controller :works do
    post '/work/create' => :create, as: 'create_work'
    delete '/work/:id/destroy' => :destroy, as: 'destroy_work'
    get '/work/:id/edit' => :edit, as: 'edit_work'
    patch '/work/:id/update' => :update, as: 'update_work'
  end

  root 'browse#jobs'

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  before_filter :authenticate_user!

  def contact_page
    if params[:username]
      @user = User.where('LOWER(username) = ?', params[:username].downcase).first
    end

    if !@user or @user == current_user
      redirect_to root_path
    end
  end

  def send_contact_request
    @errors = []
    can_send = true
    if params[:message]
      @message = params[:message].strip
    end
    if params[:username]
      @user = User.where('LOWER(username) = ?', params[:username].downcase).first
    end

    if @message and @message.blank?
      @errors << I18n.t('message_cant_be_blank')
      @message_failed = true
      can_send = false
    end
    if !verify_recaptcha
      @errors << I18n.t('recaptcha_error')
      can_send = false
    end

    if can_send and @user and @user != current_user
      ContactMailer.contact_form(current_user, @user, @message).deliver
      redirect_to root_path, notice: I18n.t('message_sent')
    else
      if @user
        render :contact_page
      else
        redirect_to root_path
      end
    end
  end

end

app/helpers/contact_helper.rb
module ContactHelper
end

app/views/contact/contact_page.html.haml
.col-md-3
.col-md-6
  .content
    .text-center
      = image_tag @user.avatar_url(:smaller), class: 'img-circle smaller'
      %h1= @user.name
      - if @user.company and !@user.company.blank?
        %h4
          %i= @user.company
    %br
    %h2.text-center= t('contact')
    = form_tag send_contact_request_path do

      = hidden_field_tag :username, @user.username

      - if @errors
        .alert.alert-danger.alert-dismissible{role: "alert"}
          %button.close{"data-dismiss" => "alert", type: "button"}
            %span{"aria-hidden" => "true"} ×
            %span.sr-only= t('close')
          %h4.text-center= t('error')
          - @errors.each do |e|
            %p.text-center= e
            

          
      - if !@message_failed
        .form-group
          = label_tag :message, t('message'), class: 'control-label'
          = text_area_tag :message, @message || '', class: 'form-control input-lg', placeholder: t('contact_placeholder'), style: 'resize:none;', rows: 5
      - else
        .form-group.has-error.has-feedback
          = label_tag :message, t('message'), class: 'control-label'
          = text_area_tag :message, @message || '', class: 'form-control input-lg', placeholder: t('contact_placeholder'), style: 'resize:none;', rows: 5
          %span.glyphicon.glyphicon-remove.form-control-feedback

      %br

      .captcha-center
        = recaptcha_tags ajax: true, display: { ssl: true, theme: 'clean' , tabindex: 1, public_key: ENV['RECAPTCHA_PUBLIC_KEY'] }

      %br
      %div.text-center
        = button_tag "<span class='glyphicon glyphicon-send'></span> #{t('send')}".html_safe, type: 'submit', class: 'btn btn-success btn-lg', data: {disable_with: t('processing')}
.col-md-3